### ISSUE TITLE
rtirl-obs/api Module not found: Error

### ISSUE THREAD

**Issue by scallensc** [muxable/rtirl-obs#122]
Module not found: Error: Package path . is not exported from package node_modules\@rtirl\api (see exports field in node_modules\@rtirl\api\package.json)  

Resolve by editing package.json exports as follows:
```
  "exports": {
    ".": "./lib"
  },
  ```

**Comment by juaoose** [comment]
Our export is a bit weird right now :P, thanks for bringing this up, I had completely forgotten about it.

In the meanwhile, I believe a working import is `import * as RealtimeIRL from '@rtirl/api/.'`
